Add new Ransac methods for PnP based on USAC included in opencv since…
SolarFramework/SolARModuleOpenCV pull request #55
Opened 2022-07-06 07:40 UTC by granger35

2022-07-07 08:55 UTC, jim-bcom requested changes

2022-08-16 15:11 UTC, merged

2022-08-22 16:42 UTC, duongnamduong commented on src/SolARPoseEstimationSACPnpOpencv.cpp
> +        LOG_WARNING("Pnp method called {} does not exist. Method ITERATIVE will be used instead", m_method);
Resolved

2022-08-22 16:42 UTC, duongnamduong commented on src/SolARPoseEstimationSACPnpOpencv.cpp
> +             in2d.push_back(cv::Point2f(imagePoints[inliers_cv.at<int>(i)].getX(),imagePoints[inliers_cv.at<int>(i)].getY()));
This code is removed

2022-08-22 16:42 UTC, duongnamduong commented on src/SolARPoseEstimationSACPnpOpencv.cpp
> +        for (unsigned int i = 0; i < projected3D.size(); i++){
Resolved

2022-08-22 16:42 UTC, duongnamduong commented on src/SolARPoseEstimationSACPnpOpencv.cpp
> +        for (unsigned int i = 0; i < inliers_cv.rows; i++){
Resolved

2022-08-22 16:42 UTC, duongnamduong commented on src/SolARPoseEstimationSACPnpOpencv.cpp
>          method = cv::SOLVEPNP_ITERATIVE;
This code is removed

2022-08-22 16:43 UTC, duongnamduong commented on src/SolARPoseEstimationSACPnpOpencv.cpp
> +    }
removed

2022-08-22 16:43 UTC, duongnamduong commented on src/SolARPoseEstimationSACPnpOpencv.cpp
> +
removed

2022-08-22 16:43 UTC, duongnamduong commented on tests/SolARTest_ModuleOpenCV_PnP/SolARTest_ModuleOpenCV_PnP_conf.xml
> +        <configure component="SolARPoseEstimationSACPnpOpencv" name="USAC PARALLEL">
Resolved

2022-08-22 16:43 UTC, duongnamduong commented on tests/SolARTest_ModuleOpenCV_PnP/experiment_helpers.hpp
> +/******************************************************************************
removed

2022-08-22 16:43 UTC, duongnamduong commented on tests/SolARTest_ModuleOpenCV_PnP/main.cpp
> +#include <iostream>
Resolved

2022-08-22 16:43 UTC, duongnamduong commented on tests/SolARTest_ModuleOpenCV_PnP/main.cpp
> +#include "random_generators.hpp"
Resolved

2022-08-22 16:43 UTC, duongnamduong commented on tests/SolARTest_ModuleOpenCV_PnP/main.cpp
> +#include "xpcf/xpcf.h"
Resolved

2022-08-22 16:44 UTC, duongnamduong commented on tests/SolARTest_ModuleOpenCV_PnP/main.cpp
> +#include "api/solver/pose/I3DTransformFinderFrom2D3D.h"
Resolved

2022-08-22 16:44 UTC, duongnamduong commented on src/SolARPoseEstimationSACPnpOpencv.cpp
> +        cv::solvePnP(in3d, in2d, m_camMatrix, m_camDistorsion, raux,taux, true, postPNPMethod);
removed

2022-08-22 16:44 UTC, duongnamduong commented on src/SolARPoseEstimationSACPnpOpencv.cpp
> +        if (postPNPMethod < cv::SOLVEPNP_ITERATIVE || postPNPMethod > cv::SOLVEPNP_IPPE_SQUARE)
removed